version: 2
jobs:
    lint:
        docker:
            - image: circleci/python:3.7.4
        steps:
            - checkout
            - run: sudo pip install pipenv
            - run:
                command: |
                    pipenv install --dev
                    pipenv run flake8
                    pipenv run black . --check
    unittest:
        docker:
            - image: circleci/python:3.7.4

        steps:
            - checkout
            - run: sudo pip install pipenv
            - run:
                command: |
                    pipenv install --dev
            - run:
                command: |
                    pipenv run mypy --ignore-missing-imports postgrespy
                    pipenv run mypy --ignore-missing-imports tests

workflows:
    version: 2
    test:
        jobs:
            - lint
            - unittest

